---
- hosts: webhosts
  become: True
  tasks:
  - name: Remove default ROOT app
    file: 
      path: /home/chfu/apache-tomcat-9.0.36/webapps/ROOT/
      state: absent
  - name: Deploy the WAR file
    copy: 
      src: ../app/target/ROOT.war
      dest: /home/chfu/apache-tomcat-9.0.36/webapps/

